--liquibase formatted sql

-- Migration: 027-reset-narration-for-voice-change
-- Purpose: Switch the read-aloud voice to ElevenLabs. Invalidate every cached narration
--          (generated by the old Gemini TTS / Web Speech path) so each tale re-synthesizes
--          with the new voice on next open. Lazy: NarrationService/claimNarration picks up
--          rows in status NONE, so resetting to NONE triggers on-demand re-generation.
-- Risk: low — DML only, no schema change. Causes a bounded one-time re-synthesis cost as
--             tales are re-opened; old audio objects in storage become orphaned (harmless).
-- Reversible: no — the previous narration_status/narration_key values are discarded and
--             cannot be restored. Re-generation is lazy and idempotent.

--changeset kazka:027-reset-narration-for-voice-change
UPDATE stories SET narration_status = 'NONE', narration_key = NULL
 WHERE narration_status IN ('READY', 'FAILED', 'GENERATING');
--rollback empty
